name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print the line
        run: echo "Good Mrng!!!"
      - name: print two lines
        run: |
            echo "Have a nice day!!!"
            echo "Thank you!!!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print these lines
        run: echo "Do the needfull..."
    
